const SYSTEM_CONFIG={inputs:[
 {id:'age',label:'Patient Age',type:'number',example:'64 years'}, {id:'stage',label:'Cancer Stage',type:'select',options:['I','II','III','IV'],example:'III'}, {id:'temperature',label:'Temperature',type:'number',example:'102.4 °F',step:'.1'}, {id:'wbc',label:'WBC Count',type:'select',options:['Low','Normal','High'],example:'Normal'}, {id:'pain',label:'Pain Level',type:'select',options:['Mild','Moderate','Severe'],example:'Moderate'}, {id:'breathing',label:'Breathing Difficulty',type:'select',options:['No','Yes'],example:'No'}
]};
const BASE_RULES=[
 {id:'R1',name:'Breathing Difficulty Rule',test:p=>p.breathing==='Yes',output:'Immediate Emergency',text:'Breathing difficulty = Yes'},
 {id:'R2',name:'Temperature + WBC Rule',test:p=>+p.temperature>101&&p.wbc==='Low',output:'High Priority',text:'Temperature > 101 AND WBC = Low'},
 {id:'R3',name:'Stage + Pain Rule',test:p=>p.stage==='IV'&&p.pain==='Severe',output:'High Priority',text:'Stage IV AND Severe Pain'},
 {id:'R4',name:'Pain Rule',test:p=>p.pain==='Severe',output:'Medium Priority',text:'Severe Pain'},
 {id:'R5',name:'Default Rule',test:()=>true,output:'Low Priority',text:'Default'}
];
const ADDITIONAL_RULE={id:'R6',name:'Oxygen Saturation Demonstration Rule',test:p=>p.oxygen!==''&&+p.oxygen<90,output:'Immediate Emergency',text:'Oxygen Saturation < 90'};
const FAILURE_CASES=[
 {id:'oxygen',title:'Missing Oxygen Saturation',tag:'MISSING INPUT',inputs:{age:68,stage:'III',temperature:99.8,wbc:'Normal',pain:'Moderate',breathing:'No',oxygen:86},missing:'Oxygen Saturation',rule:'IF oxygen saturation < 90 → Immediate Emergency',why:'The original input model has no oxygen saturation field, so its rules cannot evaluate this supplied signal.',after:'Immediate Emergency'},
 {id:'context',title:'Missing Context Variable',tag:'HYPOTHETICAL DESIGN CASE',inputs:{age:61,stage:'II',temperature:99.2,wbc:'Normal',pain:'Moderate',breathing:'No',oxygen:88},missing:'A contextual status signal',rule:'IF proposed context flag = Yes → High Priority',why:'Two hypothetical patients can look identical to the six inputs when a contextual variable is absent. This demonstrates representational limits.',after:'High Priority'},
 {id:'conflict',title:'Rule Order & Precedence',tag:'HYPOTHETICAL DESIGN CASE',inputs:{age:59,stage:'IV',temperature:100,wbc:'Normal',pain:'Severe',breathing:'Yes',oxygen:''},missing:'Explicit rule precedence',rule:'Rule 1 precedes Rule 3',why:'Both Rule 1 and Rule 3 appear relevant. The ordered engine stops at Rule 1, demonstrating that sequence is itself system logic.',after:'Immediate Emergency'}
];
let extraInput=false,extraRule=false,currentCase=null,lastPatient=null,lastBase=null;
const $=s=>document.querySelector(s); const el=(tag,props={})=>Object.assign(document.createElement(tag),props);
function renderStatic(){
 const stages=[['PATIENT','A conceptual record enters the simulation.'],['DATA COLLECTION','The system reads only its defined fields.'],['DECISION PROCESSOR','Ordered hypothetical rules evaluate one by one.'],['PRIORITY ASSIGNMENT','A simulated output is produced.'],['DOCTOR REVIEW','A person reviews the system output.'],['FEEDBACK','Missed cases and concerns are recorded.'],['SYSTEM UPDATE','Inputs and rules may be revised.']];
 $('#pipeline').append(...stages.map(([n,d])=>{let b=el('button',{className:'stage',textContent:n});b.onclick=()=>{$$('.stage.active')?.classList.remove('active');b.classList.add('active');$('#stage-detail').textContent=d};return b}));
 renderInputs();
 const outputs=[['IMMEDIATE EMERGENCY','Highest simulated priority','Ordered rule match'],['HIGH PRIORITY','Elevated simulated priority','Ordered rule match'],['MEDIUM PRIORITY','Moderate simulated priority','Ordered rule match'],['LOW PRIORITY','Default simulated priority','Default rule']];
 $('#output-cards').append(...outputs.map(x=>{let a=el('article',{className:'output-card'});a.innerHTML=`<b>${x[0]}</b><p>${x[1]}<br>Triggered by: ${x[2]}</p>`;return a}));
 $('#failure-cards').append(...FAILURE_CASES.map(c=>{let a=el('article',{className:'failure-card'});a.innerHTML=`<span class="eyebrow">${c.tag}</span><h3>${c.title}</h3><p>${c.why}</p><p><b>Missing:</b> ${c.missing}</p><button class="button">LOAD FAILURE CASE</button>`;a.querySelector('button').onclick=()=>loadFailureCase(c.id);return a}));
 const nodes=[['Data Collection','Receives the inputs defined by the current version.'],['Decision Processor','Evaluates rules in strict order.'],['Priority Assignment','Shows the simulated priority output.'],['Doctor Review','Provides human review outside automated rules.'],['Feedback','Captures concerns and missed cases.'],['System Update','Adds or revises future system logic.']];
 $('#architecture-nodes').append(...nodes.map(([n,d])=>{let b=el('button',{className:'arch-node',textContent:n});b.onclick=()=>{$$('.arch-node.active')?.classList.remove('active');b.classList.add('active');$('#arch-detail').textContent=d};return b}));
 const entities={"Cancer Patient":'Provides the conceptual patient record.',Nurses:'May collect observations for system inputs.',Oncologist:'Reviews the simulated output in the model.',Doctors:'Provide conceptual feedback.',Laboratory:'Provides measurements that may become inputs.','Medical Equipment':'May generate possible signals.','Hospital Policies':'Shape the imagined operating environment.'};
 $('#entities').append(...Object.entries(entities).map(([n,d])=>{let b=el('button',{className:'entity',textContent:n});b.onclick=()=>$('#arch-detail').textContent=`${n}: ${d}`;return b}));
}
function renderInputs(){const inputs=[...SYSTEM_CONFIG.inputs];if(extraInput)inputs.push({id:'oxygen',label:'Oxygen Saturation',type:'number',example:'86%',step:'.1',optional:true});$('#input-cards').innerHTML='';$('#form-fields').innerHTML='';inputs.forEach(i=>{let card=el('article',{className:'input-card'});card.innerHTML=`<b>${i.label.toUpperCase()}</b><span>Input type: ${i.type}<br>Example: ${i.example}</span>`;$('#input-cards').append(card);let l=el('label');l.textContent=i.label;let control;if(i.type==='select'){control=el('select',{id:i.id,required:true});control.append(el('option',{value:'',textContent:'Select…'}),...i.options.map(o=>el('option',{value:o,textContent:o})));}else control=el('input',{id:i.id,type:'number',required:!i.optional,step:i.step||'1',placeholder:i.example});l.append(control);$('#form-fields').append(l);});if(lastPatient)populate(lastPatient)}
function getPatient(){let p={};[...SYSTEM_CONFIG.inputs,...(extraInput?[{id:'oxygen'}]:[])].forEach(i=>p[i.id]=$('#'+i.id).value);return p}
function populate(p){Object.entries(p).forEach(([k,v])=>{let input=$('#'+k);if(input&&v!==undefined)input.value=v})}
function evaluate(patient,updated=false){let rules=updated&&extraRule?[ADDITIONAL_RULE,...BASE_RULES]:BASE_RULES;let trace=[];for(const rule of rules){const match=rule.test(patient);trace.push({...rule,match});if(match)return{output:rule.output,matched:rule,trace}}}
function log(lines){$('#system-log').textContent=lines.map(x=>`[${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}] ${x}`).join('\n')}
function renderDecision(result,patient,updated=false){$('#decision-empty').hidden=true;$('#decision-result').hidden=false;$('#received').textContent='INPUTS RECEIVED\n'+Object.entries(patient).filter(([k,v])=>k!=='oxygen'||extraInput).map(([k,v])=>`${k.replace(/\b\w/g,x=>x.toUpperCase())}: ${v||'not represented'}`).join('\n');$('#rule-trace').innerHTML='';result.trace.forEach((r,i)=>{let li=el('li',{textContent:`${r.id} — ${r.text}  ${r.match?'→ MATCHED':'— not matched'}`});if(r.match)li.className='matched';$('#rule-trace').append(li)});$('#result-output').textContent=`FINAL OUTPUT — ${result.output.toUpperCase()}`;let failure=currentCase&&!updated&&(currentCase.id==='oxygen'||currentCase.id==='context');$('#failure-alert').hidden=!failure;if(failure)$('#failure-alert').innerHTML=`⚠ SYSTEM LIMITATION DETECTED<br><small>${currentCase.why} Missing signal: ${currentCase.missing}.</small>`;$('#before-output').textContent=lastBase?.output?.toUpperCase()||'—';if(updated)$('#after-output').textContent=result.output.toUpperCase();log(['Patient record received','Validating inputs…','Decision processor started',...result.trace.map(r=>`${r.id} evaluated${r.match?' — matched':''}`),`Priority assigned: ${result.output}`,failure?'Potential limitation detected':'Simulation complete']);}
function run(updated=false){let p=getPatient();if(!$('#patient-form').reportValidity())return;lastPatient=p;let r=evaluate(p,updated);if(!updated)lastBase=r;renderDecision(r,p,updated);$('#feedback-output').value=r.output;return r}
function loadFailureCase(id){currentCase=FAILURE_CASES.find(c=>c.id===id);extraInput=false;extraRule=false;renderInputs();populate(currentCase.inputs);$('#new-input-title').textContent=currentCase.missing;$('#new-input-copy').textContent=currentCase.why;$('#new-rule').innerHTML=currentCase.rule.replace(' → ','<br>THEN ');$('#add-input').disabled=false;$('#add-rule').disabled=true;$('#rerun').hidden=true;$('#after-output').textContent='—';$('#system-version').textContent='VERSION 1';location.hash='simulator';log(['Failure case loaded',`Signal outside current model: ${currentCase.missing}`])}
function addInput(){extraInput=true;renderInputs();$('#add-input').disabled=true;$('#add-rule').disabled=false;$('#system-version').textContent='VERSION 2 — INPUT ADDED';log(['New input added',`${currentCase?.missing||'Oxygen Saturation'} now represented`])}
function addRule(){extraRule=true;$('#add-rule').disabled=true;$('#rerun').hidden=false;$('#system-version').textContent='VERSION 2 — RULE ADDED';log(['Proposed rule activated','Ready to re-run same patient'])}
$('#patient-form').addEventListener('submit',e=>{e.preventDefault();run(false)});$('#reset-case').onclick=()=>{currentCase=null;lastPatient=null;$('#patient-form').reset();$('#decision-result').hidden=true;$('#decision-empty').hidden=false;log(['Patient record reset'])};$('#add-input').onclick=addInput;$('#add-rule').onclick=addRule;$('#rerun').onclick=()=>run(true);
$('#feedback-form').addEventListener('submit',e=>{e.preventDefault();$('#feedback-status').textContent='FEEDBACK RECEIVED — potential system update identified. Simulation only.';log(['Doctor feedback submitted','Potential update recorded in system evolution'])});
$('.menu').onclick=()=>$('.nav nav').classList.toggle('open');
const demoSteps=[['Create patient','Use the simulator to enter a conceptual patient record.'],['Run existing system','Run the current ordered rule engine.'],['Show decision','Inspect the matched rule and trace.'],['Reveal failure','Load Missing Oxygen Saturation and run it.'],['Show missing input','Explain that version 1 cannot evaluate it.'],['Add input','Add the missing signal to version 2.'],['Add rule','Activate the proposed hypothetical rule.'],['Run again','Re-run exactly the same patient.'],['Compare','Show the before/after system outputs.'],['Feedback','Submit simulated doctor feedback.']];let step=0;function showDemo(){let s=demoSteps[step];$('#demo-title').textContent=`STEP ${step+1} — ${s[0]}`;$('#demo-copy').textContent=s[1];$('#demo-back').disabled=step===0;$('#demo-next').textContent=step===demoSteps.length-1?'FINISH':'NEXT →'}function openDemo(){document.body.classList.add('presentation');$('#demo-panel').hidden=false;step=0;showDemo();$('#simulator').scrollIntoView()}function closeDemo(){document.body.classList.remove('presentation');$('#demo-panel').hidden=true}$('.demo-toggle').onclick=openDemo;$('#demo-close').onclick=closeDemo;$('#demo-next').onclick=()=>{if(step<demoSteps.length-1){step++;showDemo()}else closeDemo()};$('#demo-back').onclick=()=>{if(step){step--;showDemo()}};document.addEventListener('keydown',e=>{if(!$('#demo-panel').hidden){if(e.key==='ArrowRight')$('#demo-next').click();if(e.key==='ArrowLeft')$('#demo-back').click();if(e.key==='Escape')closeDemo()}});
renderStatic();
